source 'https://rubygems.org'

gem 'cucumber'
gem 'capybara'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'pry'
gem 'rspec'
gem 'faker'
gem 'activesupport'
gem 'httparty'
gem 'rest-client'
gem 'require_all'
gem 'oauth2'
gem 'rspec-wait'
